### ISSUE TITLE
ISP violation

### ISSUE THREAD

**Issue by vitalk** [anastasiakoroto/LX_Task4#1]
https://github.com/anastasiakoroto/LX_Task4/blob/b5ecfc71d258d98409f78a733af4ac716f7e91a9/manager_db.py#L42

There is only one difference between `write_queries_result_to_json` and `write_queries_result_to_xml` is the class which process result of the queries. Please decompose logic to explicitly pass writer which should be used to write result. The main entry point should initialize proper data reader / writer, execute required queries and output their results to writer, e.g. reader doesn't know anything about writer and queries which you execute and vise versa.

**Comment by anastasiakoroto** [comment]
Fixed. Thank you for advice.
